/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(expo/(.*)$)|^(expo$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@workspace/(.*)$",
    "",
    "^types$",
    "^@/types/(.*)$",
    "^@/constants/(.*)$",
    "^@/config/(.*)$",
    "^@/theme/(.*)$",
    "^@/core/(.*)$",
    "^@/lib/(.*)$",
    "^@/db/(.*)$",
    "^@/hooks/(.*)$",
    "^@/modules/(.*)$",
    "^@/utils/(.*)$",
    "^@/components/icons/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/patterns/(.*)$",
    "^@/components/(.*)$",
    "^@/app/(.*)$",
    "^@/assets/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
}
