export interface ThemeColors {
    background: string;
    foreground: string;
    surface: string;
    surfaceForeground: string;
    overlay: string;
    overlayForeground: string;
    muted: string;
    accent: string;
    accentForeground: string;
    segment: string;
    segmentForeground: string;
    border: string;
    divider: string;
    focus: string;
    link: string;
    default: string;
    defaultForeground: string;
    success: string;
    successForeground: string;
    warning: string;
    warningForeground: string;
    danger: string;
    dangerForeground: string;
    field: string;
    fieldHover: string;
    fieldForeground: string;
    fieldPlaceholder: string;
    fieldBorder: string;
    fieldFocus: string;
    fieldBorderHover: string;
    fieldBorderFocus: string;
    backgroundSecondary: string;
    backgroundTertiary: string;
    backgroundInverse: string;
    defaultHover: string;
    accentHover: string;
    successHover: string;
    warningHover: string;
    dangerHover: string;
    accentSoft: string;
    accentSoftForeground: string;
    accentSoftHover: string;
    dangerSoft: string;
    dangerSoftForeground: string;
    dangerSoftHover: string;
    warningSoft: string;
    warningSoftForeground: string;
    warningSoftHover: string;
    successSoft: string;
    successSoftForeground: string;
    successSoftHover: string;
    surfaceSecondary: string;
    surfaceTertiary: string;
    onSurface: string;
    onSurfaceForeground: string;
    onSurfaceHover: string;
    onSurfaceFocus: string;
    rainbowLime: string;
    rainbowLightGreen: string;
    rainbowTeal: string;
    rainbowCyan: string;
    rainbowLightBlue: string;
    rainbowSkyBlue: string;
    rainbowBlue: string;
    rainbowIndigo: string;
    rainbowDeepPurple: string;
    rainbowPurple: string;
    rainbowMagenta: string;
    rainbowRed: string;
    rainbowOrange: string;
    rainbowAmber: string;
    rainbowYellow: string;
    rainbowNavy: string;
}

export const Colors: { light: ThemeColors; dark: ThemeColors } = {
    light: {
        background: "#ffffff",
        foreground: "#09090b",
        surface: "#ffffff",
        surfaceForeground: "#09090b",
        overlay: "#ffffff",
        overlayForeground: "#09090b",
        muted: "#71717a",
        accent: "#3b82f6",
        accentForeground: "#ffffff",
        segment: "#f4f4f5",
        segmentForeground: "#18181b",
        border: "#e4e4e7",
        divider: "#e4e4e7",
        focus: "#3b82f6",
        link: "#2563eb",
        default: "#f4f4f5",
        defaultForeground: "#18181b",
        success: "#22c55e",
        successForeground: "#ffffff",
        warning: "#f59e0b",
        warningForeground: "#ffffff",
        danger: "#ef4444",
        dangerForeground: "#ffffff",
        field: "#f4f4f5",
        fieldHover: "#ececee",
        fieldForeground: "#09090b",
        fieldPlaceholder: "#71717a",
        fieldBorder: "#e4e4e7",
        fieldFocus: "#f4f4f5",
        fieldBorderHover: "#ceced4",
        fieldBorderFocus: "#a9a9b2",
        backgroundSecondary: "#f6f6f7",
        backgroundTertiary: "#ececee",
        backgroundInverse: "#09090b",
        defaultHover: "#eeeeef",
        accentHover: "#4f8df7",
        successHover: "#38ca6f",
        warningHover: "#f6a927",
        dangerHover: "#f05a5a",
        accentSoft: "rgba(59,130,246,0.15)",
        accentSoftForeground: "#3b82f6",
        accentSoftHover: "rgba(59,130,246,0.2)",
        dangerSoft: "rgba(239,68,68,0.15)",
        dangerSoftForeground: "#ef4444",
        dangerSoftHover: "rgba(239,68,68,0.2)",
        warningSoft: "rgba(245,158,11,0.15)",
        warningSoftForeground: "#f59e0b",
        warningSoftHover: "rgba(245,158,11,0.2)",
        successSoft: "rgba(34,197,94,0.15)",
        successSoftForeground: "#22c55e",
        successSoftHover: "rgba(34,197,94,0.2)",
        surfaceSecondary: "#f0f0f1",
        surfaceTertiary: "#ebebed",
        onSurface: "#efeff0",
        onSurfaceForeground: "#09090b",
        onSurfaceHover: "#eaeaec",
        onSurfaceFocus: "#efeff0",
        rainbowLime: "#5BDD6A",
        rainbowLightGreen: "#35DB80",
        rainbowTeal: "#20D6BE",
        rainbowCyan: "#26D1D1",
        rainbowLightBlue: "#11CDF2",
        rainbowSkyBlue: "#40B6FF",
        rainbowBlue: "#638DFF",
        rainbowIndigo: "#7979F7",
        rainbowDeepPurple: "#A17DF5",
        rainbowPurple: "#CE7AF0",
        rainbowMagenta: "#FF70B0",
        rainbowRed: "#FF697A",
        rainbowOrange: "#FF875C",
        rainbowAmber: "#FFD86B",
        rainbowYellow: "#FDFF78",
        rainbowNavy: "#98A0B3",
    },
    dark: {
        background: "#09090b",
        foreground: "#fafafa",
        surface: "#09090b",
        surfaceForeground: "#fafafa",
        overlay: "#09090b",
        overlayForeground: "#fafafa",
        muted: "#a1a1aa",
        accent: "#3b82f6",
        accentForeground: "#ffffff",
        segment: "#27272a",
        segmentForeground: "#fafafa",
        border: "#27272a",
        divider: "#27272a",
        focus: "#3b82f6",
        link: "#3b82f6",
        default: "#27272a",
        defaultForeground: "#fafafa",
        success: "#22c55e",
        successForeground: "#ffffff",
        warning: "#f59e0b",
        warningForeground: "#ffffff",
        danger: "#ef4444",
        dangerForeground: "#ffffff",
        field: "#27272a",
        fieldHover: "#2f2f33",
        fieldForeground: "#fafafa",
        fieldPlaceholder: "#a1a1aa",
        fieldBorder: "#27272a",
        fieldFocus: "#27272a",
        fieldBorderHover: "#4f4f56",
        fieldBorderFocus: "#707078",
        backgroundSecondary: "#121214",
        backgroundTertiary: "#1a1a1d",
        backgroundInverse: "#fafafa",
        defaultHover: "#2f2f33",
        accentHover: "#4f8df7",
        successHover: "#38ca6f",
        warningHover: "#f6a927",
        dangerHover: "#f05a5a",
        accentSoft: "rgba(59,130,246,0.15)",
        accentSoftForeground: "#3b82f6",
        accentSoftHover: "rgba(59,130,246,0.2)",
        dangerSoft: "rgba(239,68,68,0.15)",
        dangerSoftForeground: "#ef4444",
        dangerSoftHover: "rgba(239,68,68,0.2)",
        warningSoft: "rgba(245,158,11,0.15)",
        warningSoftForeground: "#f59e0b",
        warningSoftHover: "rgba(245,158,11,0.2)",
        successSoft: "rgba(34,197,94,0.15)",
        successSoftForeground: "#22c55e",
        successSoftHover: "rgba(34,197,94,0.2)",
        surfaceSecondary: "#17171a",
        surfaceTertiary: "#1d1d20",
        onSurface: "#1a1a1d",
        onSurfaceForeground: "#fafafa",
        onSurfaceHover: "#202024",
        onSurfaceFocus: "#1a1a1d",
        rainbowLime: "#5BDD6A",
        rainbowLightGreen: "#35DB80",
        rainbowTeal: "#20D6BE",
        rainbowCyan: "#26D1D1",
        rainbowLightBlue: "#11CDF2",
        rainbowSkyBlue: "#40B6FF",
        rainbowBlue: "#638DFF",
        rainbowIndigo: "#7979F7",
        rainbowDeepPurple: "#A17DF5",
        rainbowPurple: "#CE7AF0",
        rainbowMagenta: "#FF70B0",
        rainbowRed: "#FF697A",
        rainbowOrange: "#FF875C",
        rainbowAmber: "#FFD86B",
        rainbowYellow: "#FDFF78",
        rainbowNavy: "#98A0B3",
    },
};
