// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'theme-default-light', 'theme-default-dark', 'theme-nord-light', 'theme-nord-dark']
    }
}

export {}
